import { NgModule } from '@angular/core';
import {
  MatToolbarModule,
  MatButtonModule,
  MatSidenavModule,
  MatTableModule,
  MatDialogModule,
  MatCardModule,
  MatRadioModule,
  MatIconModule,
  MatFormFieldModule,
  MatSelectModule,
  MatMenuModule,
  MatDividerModule,
  MatNativeDateModule ,
  MatCheckboxModule,
  MatInputModule,
  MatGridListModule,
  MatDatepickerModule,
  MatSortModule,
  MatTabsModule, 
  MatPaginatorModule,
} from '@angular/material';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

@NgModule({
  imports: [
      MatToolbarModule,
      MatGridListModule,
      MatSidenavModule,
      MatTableModule,
      MatCardModule,
      MatInputModule,
      MatFormFieldModule,
      MatSelectModule,
      MatCheckboxModule,
      MatRadioModule,
      MatIconModule,
      MatDialogModule,
      MatMenuModule,
      MatDividerModule,
      MatButtonModule,
      MatNativeDateModule ,
      BrowserAnimationsModule,
      MatDatepickerModule,
      MatSortModule,
      MatTabsModule, 
      MatPaginatorModule,
      MatRadioModule
      
  ],
  exports: [
      MatToolbarModule,
      MatInputModule,
      MatSidenavModule,
      MatFormFieldModule,
      MatDialogModule,
      MatCheckboxModule,
      MatTableModule,
      MatRadioModule,
      MatSelectModule,
      MatNativeDateModule,
      MatIconModule,
      MatMenuModule,
      MatDividerModule,
      MatCardModule,
      MatGridListModule,
      MatButtonModule,
      BrowserAnimationsModule,
      MatDatepickerModule,
      MatSortModule,
      MatTabsModule,
      MatPaginatorModule,
      MatRadioModule
  ],
})
export class MaterialModule { }
